version: "3.1"

services:
  postgres:
    image: hub.hamdocker.ir/postgres
    restart: always
    env_file: ${ENV:-.env}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
