version: "3.1"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ${ENV:-.env}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: hub.hamdocker.ir/postgres
    restart: always
    env_file: ${ENV:-.env}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
