# Generated by Django 5.1 on 2024-10-03 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_create_plans_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='vote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.plan')),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
