# Generated by Django 5.1 on 2024-10-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_create_votes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_voters', models.IntegerField(default=0, verbose_name='totalVoters')),
                ('votes_average', models.FloatField(default=0, verbose_name='votesAverage')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
        ),
    ]
